/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * principal.java
 *
 * Created on 04/10/2009, 22:04:55
 */

package splash;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.*;

public class principal extends javax.swing.JFrame {

    /** Creates new form principal */
    public principal() {
        initComponents();
                this.setLocationRelativeTo(null);
    }
public class efecto implements Runnable{ //efecto de la ventana buscar
    Thread t;
    @SuppressWarnings("static-access")
    public void run () {
            for (int i=-990; i<=80 ;i=i+50){
                try {
                    t.sleep(2);
                     panelcli.setLocation(i, 80);
                     } catch (InterruptedException ex) {
                    Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
                }
              }

  }
}
public class efecto_inverso implements Runnable{ //efecto retroceso de la ventana buscar
    Thread t2;
    @SuppressWarnings("static-access")
    public void run () {
            for (int i=60; i>=-1000 ;i=i-50){
                try {
                    t2.sleep(2);
                     panelcli.setLocation(i, 80);
                } catch (InterruptedException ex) {
                    Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
                }
              }

  }
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        panelcli = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        cliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        calendarComponent1 = new com.imagine.component.calendar.CalendarComponent();
        jButton13 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();

        jMenuItem2.setText("Nuevo Cliente");

        jMenuItem3.setText("Editar Cliente");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(177, 177, 177));
        setMinimumSize(new java.awt.Dimension(1014, 770));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelcli.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelcli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("HORARIOS"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DIA", "HORA INICIO", "HORA FINAL", "TOTAL ", "PROFESIONAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 510, 140));

        panelcli.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 530, 210));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cliente desde : 10 de Octubre de 2009");
        panelcli.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 260, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("SALDO A FAVOR DE $ 80");
        panelcli.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 260, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel7.setText("GATES, Bill");
        panelcli.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 250, 30));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ultimas 5 Asistencias"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DIA", "FECHA", "HORA", "TIPO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 400, 150));

        panelcli.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 440, 230));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("RUTINA"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("\nAqui va la rutina");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 390, 170));

        panelcli.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 430, 210));
        jPanel6.getAccessibleContext().setAccessibleName("Rutina");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel6.setText("Tu última visita fue: \"ULTIMA VISITA\"");
        panelcli.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 260, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("SALDO PENDIENTE DE $ 40000");
        panelcli.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 260, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelcli.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operaciones/bill [320x200].jpg"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelcli.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 190));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/32x32/accept.png"))); // NOI18N
        jButton8.setText("Empezar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        panelcli.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 210, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel12.setText("ESTADO DE CUENTA :  VENCIDA");
        panelcli.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 260, 40));

        jButton16.setText("Realizar Pago del Cliente");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        panelcli.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 210, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel14.setText("2 Agosto del 2009");
        panelcli.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 140, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel15.setText("00:00");
        panelcli.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 80, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel17.setText("Fecha");
        panelcli.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 40, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel18.setText("Hora");
        panelcli.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 40, -1));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/back_1.png"))); // NOI18N
        jButton21.setMaximumSize(new java.awt.Dimension(143, 55));
        jButton21.setMinimumSize(new java.awt.Dimension(173, 55));
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton21MouseClicked(evt);
            }
        });
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        panelcli.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 40, 50));

        getContentPane().add(panelcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(-940, 70, 1010, 520));

        cliente.setFont(new java.awt.Font("Tahoma", 1, 18));
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        getContentPane().add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 330, 30));

        jLabel1.setText("Buscar Cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/users.png"))); // NOI18N
        jButton4.setText("CLIENTES");
        jButton4.setMaximumSize(new java.awt.Dimension(143, 53));
        jButton4.setMinimumSize(new java.awt.Dimension(173, 55));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/clock.png"))); // NOI18N
        jButton5.setText("HORARIOS");
        jButton5.setMaximumSize(new java.awt.Dimension(143, 55));
        jButton5.setMinimumSize(new java.awt.Dimension(173, 55));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/attachment.png"))); // NOI18N
        jButton6.setText("RUTINAS");
        jButton6.setMaximumSize(new java.awt.Dimension(143, 55));
        jButton6.setMinimumSize(new java.awt.Dimension(173, 55));
        jPanel2.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/user.png"))); // NOI18N
        jButton7.setText("EMPLEADOS");
        jButton7.setMaximumSize(new java.awt.Dimension(143, 55));
        jButton7.setMinimumSize(new java.awt.Dimension(173, 55));
        jPanel2.add(jButton7);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/chart.png"))); // NOI18N
        jButton9.setText("INFORMES");
        jButton9.setMaximumSize(new java.awt.Dimension(143, 55));
        jButton9.setMinimumSize(new java.awt.Dimension(173, 55));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel2.add(jButton9);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1100, -1));

        jLabel5.setText("Búsqueda por Nombre, Apellido o DNI");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel9.setText("Total Asistencias Registradas:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 690, 210, -1));

        jLabel10.setText("Usuario en Sesión:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 150, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre Cliente", "Empleado", "Hora Inicio", "Hora Final", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 650, 470));
        getContentPane().add(calendarComponent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, -1, 160));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/find.png"))); // NOI18N
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 50, 40));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("CLIENTES EN EL GIMNASIO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 210, 30));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/add.png"))); // NOI18N
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 50, 40));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/clock.png"))); // NOI18N
        jButton18.setMaximumSize(new java.awt.Dimension(143, 55));
        jButton18.setMinimumSize(new java.awt.Dimension(173, 55));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, 40));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/delete.png"))); // NOI18N
        jButton19.setMaximumSize(new java.awt.Dimension(143, 55));
        jButton19.setMinimumSize(new java.awt.Dimension(173, 55));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, 40));

        jLabel11.setText("INFORMACION");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 190, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 190, 250));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 1090, 10));

        jMenu8.setText("Archivo");

        jMenu9.setText("Cerrar Sesión");
        jMenu8.add(jMenu9);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Salir");
        jMenu8.add(jMenuItem1);

        jMenuBar2.add(jMenu8);

        jMenu10.setText("Clientes");

        jMenuItem8.setText("Busqueda Avanzada");
        jMenu10.add(jMenuItem8);
        jMenu10.add(jSeparator2);
        jMenu10.add(jSeparator3);

        jMenu15.setText("Foto del Cliente");

        jMenuItem6.setText("Importar Foto");
        jMenu15.add(jMenuItem6);

        jMenu10.add(jMenu15);
        jMenu10.add(jSeparator4);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem7.setText("Hacer un Pago");
        jMenu10.add(jMenuItem7);

        jMenuItem9.setText("Ver Todas Asistencias");
        jMenu10.add(jMenuItem9);

        jMenuItem10.setText("Ver todos los Clientes");
        jMenu10.add(jMenuItem10);

        jMenuBar2.add(jMenu10);

        jMenu12.setText("Administración");

        jMenuItem11.setText("Administrar a (nombre cliente)");
        jMenu12.add(jMenuItem11);
        jMenu12.add(jSeparator5);

        jMenuItem12.setText("Administrar Empleados");
        jMenu12.add(jMenuItem12);

        jMenuItem13.setText("Administrar Visitas");
        jMenu12.add(jMenuItem13);

        jMenuItem14.setText("Administrar Cuentas");
        jMenu12.add(jMenuItem14);

        jMenuBar2.add(jMenu12);

        jMenu13.setText("Informes");

        jMenu11.setText("Socios");

        jMenuItem15.setText("Lista de todos los clientes");
        jMenu11.add(jMenuItem15);

        jMenuItem16.setText("Clientes con vencimiento");
        jMenu11.add(jMenuItem16);

        jMenuItem17.setText("Clientes al Dia");
        jMenu11.add(jMenuItem17);

        jMenu13.add(jMenu11);

        jMenu16.setText("Asistencia");

        jMenuItem18.setText("Lista de clientes que ingresaron por fecha");
        jMenu16.add(jMenuItem18);

        jMenuItem19.setText("Lista de invitados");
        jMenu16.add(jMenuItem19);

        jMenuItem20.setText("Asistencia por hora");
        jMenu16.add(jMenuItem20);

        jMenu13.add(jMenu16);

        jMenu17.setText("Pagos");

        jMenuItem21.setText("Pagos por Fecha");
        jMenu17.add(jMenuItem21);

        jMenuItem22.setText("Suma total de Pagos por periodo de tiempo");
        jMenu17.add(jMenuItem22);

        jMenuItem23.setText("Saldo pendiente de clientes vencidos");
        jMenu17.add(jMenuItem23);

        jMenu13.add(jMenu17);

        jMenuBar2.add(jMenu13);

        jMenu14.setText("Ayuda");

        jMenuItem24.setText("Ayuda");
        jMenu14.add(jMenuItem24);

        jMenuItem25.setText("Acerca de este Programa");
        jMenu14.add(jMenuItem25);

        jMenuBar2.add(jMenu14);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
          panelcli.setLocation(-990, 80);
     /*ImageIcon icono=new ImageIcon("/splash/P280809_17.28.jpg");
Image img = icono.getImage();
Image newimg = img.getScaledInstance(100, 200,  java.awt.Image.SCALE_SMOOTH);
ImageIcon newIcon = new ImageIcon(newimg);
jLabel2.setIcon(newIcon);
//jLabel2.setSize(350, 450);*/
       //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splash/P280809_17.28.jpg")));

      
    }//GEN-LAST:event_formComponentShown

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        new operaciones.agregar_cliente().setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
          new Thread(new efecto()).start();
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked


    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
new operaciones.realizar_pago().setVisible(true);
    }//GEN-LAST:event_jButton8MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        new operaciones.Horario().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseClicked
        new Thread(new efecto_inverso()).start();

    }//GEN-LAST:event_jButton21MouseClicked

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.imagine.component.calendar.CalendarComponent calendarComponent1;
    private javax.swing.JTextField cliente;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    public javax.swing.JPanel panelcli;
    // End of variables declaration//GEN-END:variables

}
